language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
  - "python -m pip install -U pip"
  - "pip install --upgrade setuptools"
  - "pip install -r requirements-dev.txt"

script:
  - invoke tests
