# -*- coding: utf-8 -*-
from __future__ import absolute_import

DEFAULT_SELECTOR_SEP = '/'
DEFAULT_SEARCH_DN_DEPTH = 3
DEFAULT_SEARCH_UP_DEPTH = 0
DEFAULT_SEARCH_DN_LEVELS = 0
DEFAULT_SEARCH_UP_LEVELS = 0
DOWN = 0
UP = 1
